# Generated by Django 2.2.8 on 2021-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=30, verbose_name='简介'),
        ),
    ]
